### PR TITLE
bt2: typo staitc -> static

### PR DESCRIPTION
**Pull request by frdeso**
Signed-off-by: Francis Deslauriers <francis.deslauriers@efficios.com>

### CODE REVIEW

**Comment by frdeso** [comment]
Would you prefer this PR to be compared against the optimalize branch?

**Comment by eepp** [comment]
> Would you prefer this PR to be compared against the optimalize branch?

Yes let's focus on this branch for short-term new development.

**Comment by eepp** [comment]
For everything related to the `bt2` Python bindings, you can use the `bt2:` prefix for the patch's subject line.

**Comment by frdeso** [comment]
Updated the commit message and PR branch.

**Pull request merged**
